### ISSUE TITLE
Qt5基础问题

### ISSUE THREAD

**Issue by hqwx2018** [Chorior/Chorior.github.io#1]
原文：另一个实现模态对话框的方式是使用 QWidget::setWindowModality，但是只对不可见的窗口有效。
应该改为：另一个实现模态对话框的方式是使用 QWidget::setWindowModality，需要先hide()再show()。
From:  https://chorior.github.io/2017/08/28/Qt5-basis/#overview

**Comment by Chorior** [comment]
hide之后就是不可见了嘛
